import type { DeptFieldFragments } from '../types';

// Paediatric field fragments — SA state-hospital conventions: everything is
// weighed (prescribing is mg/kg), plotted (RTHB growth curves), screened
// (IMCI danger signs), and checked against the EPI schedule. Neonates are
// framed by day of life; the SAM corner runs on the WHO ten steps.

export const paedsFields: DeptFieldFragments = {
  intake: d => [
    { key: 'weight', label: 'Weight (kg)', value: d.weight ?? '', hint: 'today\'s ACTUAL weight — every paediatric prescription is mg/kg; an estimated or stale weight is a dosing error waiting to happen. Age-based formulas (term-1y ≈ (age in months + 9)/2; 1-5y ≈ 2×(age+5); 6-12y ≈ 3×age+7) are a resuscitation-only fallback when no scale is available in an emergency — never a substitute for a real weight once one can be obtained', placeholder: 'e.g. 8.4 kg (weighed today)' },
    { key: 'rthb', label: 'RTHB (Road to Health Book)', value: d.rthb ?? '', kind: 'select', options: ['Seen — with patient', 'Not brought — ask caregiver to bring', 'Lost — issue new & rebuild record'], hint: 'ask for it at EVERY encounter, not just admission — it plots the growth TREND (centile-crossing reveals chronic illness that one weight alone cannot) and lets you verify immunisations against the record rather than caregiver memory. It is frequently the single most useful piece of information in the whole consultation, and "not brought"/incomplete is itself a marker worth noting, not just a logistics gap' },
    { key: 'immunisations', label: 'Immunisations', value: d.immunisations ?? '', hint: 'from the RTHB page, not caregiver memory — checked against the SA EPI schedule for age. EPI-SA 2024: birth BCG/OPV0, 6/10/14-week hexavalent+PCV10+rotavirus, 9-month measles+PCV booster, 18-month measles+DTaP-IPV+Hib boosters. Catch-up follows minimum-interval rules — EXCEPT rotavirus, which has a hard 24-week cut-off and cannot be given or caught up after that age', placeholder: 'Up to date / behind (which dose) / unknown' },
    { key: 'birthHistory', label: 'Birth History', value: d.birthHistory ?? '', hint: 'gestation, mode of delivery, birth weight, complications — prematurity changes corrected age, growth targets and risk for years', placeholder: 'e.g. term NVD, BW 3.2kg, no complications' },
    { key: 'caregiver', label: 'Caregiver', value: d.caregiver ?? '', hint: 'who is the historian and who takes the child home — consent, feeding and follow-up all run through this person', placeholder: 'Parent/guardian name + relationship' },
  ],

  history: {
    insertAt: 2,
    fields: (d, subDept) => {
      if (subDept === 'neonatal') {
        return [
          { key: 'birthDetails', label: 'Birth Details', value: d.birthDetails ?? '', kind: 'textarea', hint: 'gestation at birth, birth weight, mode of delivery, APGARs 1/5min, resuscitation needed (bag-mask? how long?) — the APGARs and resus story predict today\'s problems (HIE, feeding, glucose)', placeholder: 'e.g. 34w EMCS for PET, BW 1.9kg, APGAR 6/8, bag-mask 1 min' },
          { key: 'maternalRisk', label: 'Maternal / Perinatal Risk', value: d.maternalRisk ?? '', kind: 'textarea', hint: 'the neonatal sepsis and congenital-infection screen lives in the MOTHER\'s file: HIV (+PMTCT given?), RPR result & treatment doses, ROM ≥18h, maternal fever in labour, GBS. Any ONE of these is enough to start an early-onset septic screen — SA units also see a disproportionate share of Klebsiella/Gram-negative EOS from nosocomial pressure even in "early" presentations, so treat and culture rather than waiting for risk factors to combine', placeholder: 'e.g. mother HIV+ on ART VL suppressed; RPR neg; ROM 6h; no fever' },
          { key: 'hivExposure', label: 'HIV Exposure & Prophylaxis', value: d.hivExposure ?? '', kind: 'textarea', hint: 'ALL HIV-exposed infants get DUAL prophylaxis — NVP + AZT — from birth for a full 6 weeks by default, regardless of risk tier; the risk tier (from the maternal VIRAL LOAD around delivery, not just "on ART or not") refines duration/intensity and testing frequency, it does not decide whether AZT is added. Document the maternal delivery VL result (or "pending") in the infant\'s own notes — the pathway can\'t be correctly assigned without it. Birth PCR within 48h detects in-utero transmission — a positive result is a same-day ART discussion, not a routine result for the next visit. Testing cascade: birth PCR → ~10-week PCR → ~6-month PCR if breastfeeding → ~9-month rapid antibody → confirmatory test after breastfeeding stops. Mixed feeding in the first 6 months is specifically discouraged', placeholder: 'e.g. HIV-exposed, mother VL suppressed on ART (low risk); birth PCR sent/pending; NVP+AZT started — or not exposed' },
          { key: 'feeding', label: 'Feeding', value: d.feeding ?? '', kind: 'textarea', hint: 'route (breast/cup/NG), volumes calculated per kg — day 1 starts ~60 ml/kg/day, advancing ~20-30/day to 150-180 ml/kg/day; "feeding well" is not a number', placeholder: 'e.g. EBM via NG, 45ml 3-hourly = 150 ml/kg/day, tolerated' },
        ];
      }
      if (subDept === 'malnutrition') {
        return [
          { key: 'nutritionHistory', label: 'Nutrition History', value: d.nutritionHistory ?? '', kind: 'textarea', hint: '24-hour dietary recall, breastfeeding history, when and why feeding changed, food security at home, who feeds the child — SAM is a household diagnosis, not just a child\'s', placeholder: '24h recall, weaning story, food security, who feeds the child' },
          { key: 'tbHivScreen', label: 'TB / HIV Screen', value: d.tbHivScreen ?? '', hint: 'every SAM child is HIV and TB until excluded — HIV test THIS admission, TB contact + symptom screen; SAM that doesn\'t respond to feeding is untreated TB or HIV', placeholder: 'e.g. HIV test sent, no known TB contact, cough 3 weeks — sputum/GA sent' },
          { key: 'socialCircumstances', label: 'Social Circumstances', value: d.socialCircumstances ?? '', kind: 'textarea', hint: 'grants (CSG in place?), who else is in the house, previous SAM admissions, social-worker involvement — the relapse is prevented here, not with the feeds', placeholder: 'e.g. CSG not yet accessed — refer social worker; 3 siblings' },
        ];
      }
      return [
        { key: 'development', label: 'Development', value: d.development ?? '', kind: 'textarea', hint: 'milestones for age across all four domains — regression (losing milestones) is a red flag, not a variant; correct for prematurity until 2 years', placeholder: 'Gross motor, fine motor, language, social — for (corrected) age' },
        { key: 'developmentalRedFlags', label: 'Developmental Red Flags', value: d.developmentalRedFlags ?? '', kind: 'select', options: ['None — milestones age-appropriate across all domains', 'Regression — loss of a previously acquired skill', 'Gross motor delay past refer-now age', 'Language delay past refer-now age', 'No pointing / joint attention by 18 months', 'Persistent primitive reflex / marked asymmetry of tone or movement', 'More than one domain affected'], hint: 'a discrete refer-NOW screen, not a repeat of the milestones narrative above: no social smile by 3 months, persistent head lag by 4 months, not sitting by 9-10 months, not walking by 18 months, no words by 15-18 months, no pointing/joint attention by 18 months (autism flag), a primitive reflex persisting past its disappearance age, or ANY loss of a previously-acquired skill at any age — these override "still within the wide range of normal" reassurance and warrant assessment regardless of which chart you were using', placeholder: '' },
        { key: 'feeding', label: 'Feeding / Nutrition', value: d.feeding ?? '', kind: 'textarea', hint: 'breast/formula/solids, appetite, recent change — "stopped eating" in a child carries the weight "chest pain" carries in an adult', placeholder: 'Feeding pattern, appetite, recent changes' },
        { key: 'tbContact', label: 'TB Contact', value: d.tbContact ?? '', hint: 'anyone in the household with TB or a chronic cough? A child <5 in contact with TB qualifies for preventive therapy even when well — asking is the intervention', placeholder: 'e.g. no known contact — or uncle on TB treatment, same house' },
        { key: 'hivExposurePcr', label: 'HIV Exposure / PCR', value: d.hivExposurePcr ?? '', hint: 'maternal status + child\'s last test (PCR <18 months, rapid after) from the RTHB page — an HIV-exposed child with no documented test needs one THIS visit. Full pathway: birth PCR (48h) → ~10-week PCR → ~6-month PCR if breastfeeding → ~9-month rapid antibody → confirmatory test after breastfeeding stops; any reactive/positive result at any point is same-day-action, not "repeat at the next scheduled visit". HIV exposure does not usually change the EPI-SA schedule, but live vaccines need caution once the child is confirmed HIV-infected/immunocompromised', placeholder: 'e.g. mother HIV+, child PCR neg at 10w, repeat due' },
      ];
    },
  },

  assessment: {
    // After General + Focused exam (index 4), before Investigations.
    insertAt: 4,
    fields: (d, subDept) => {
      if (subDept === 'neonatal') {
        return [
          { key: 'dayOfLife', label: 'Day of Life', value: d.dayOfLife ?? '', hint: 'every neonatal number is read against day of life — bilirubin thresholds, expected weight change, feed volumes, sepsis pattern (day 0-3 = maternal origin, later = environment)', placeholder: 'e.g. day 3 of life' },
          { key: 'growth', label: 'Weight vs Birth Weight', value: d.growth ?? '', hint: 'weigh daily and compute % change from birth weight — up to 10% loss is physiological, regained by day 10-14; >10% = formal feeding assessment + sodium, not reassurance', placeholder: 'e.g. 1.85kg (BW 1.9kg, -2.6%); HC 31cm' },
          { key: 'jaundice', label: 'Jaundice (hours of life)', value: d.jaundice ?? '', hint: 'always anchor to HOURS of life — visible jaundice <24h is ALWAYS pathological (haemolysis until proven otherwise); plot TSB on the hour-specific, gestation- and risk-banded chart, never judge a bilirubin against a single memorised number. Check stool/urine colour and FRACTIONATE (conjugated/direct) if jaundice persists beyond 2 weeks (3 if breastfed and otherwise well) — conjugated jaundice is NEVER physiological, and the biliary atresia clock (best outcomes with surgery before ~45-60 days of life) makes this one of the few "refer today, don\'t wait for it to declare itself" calls in paediatrics. Transcutaneous readings are unreliable once phototherapy has started or in darker skin tones — confirm with serum TSB', placeholder: 'e.g. jaundiced to trunk at 52h, TSB 240 — below photo line' },
          { key: 'feedsAndOutput', label: 'Feeds & Output Today', value: d.feedsAndOutput ?? '', hint: 'ml/kg/day actually TAKEN (not prescribed), vomits, urine + stool count — a neonate refusing feeds is septic until proven otherwise', placeholder: 'e.g. tolerating 150 ml/kg/day, no vomits, 6 wet nappies, stooling' },
          { key: 'neonatalDangerSigns', label: 'Neonatal Danger Signs', value: d.neonatalDangerSigns ?? '', hint: 'poor feeding, temperature instability (hypothermia counts MORE than fever), apnoea, convulsions, lethargy — any ONE in a neonate = presume sepsis: culture and treat, don\'t observe', placeholder: 'e.g. none — feeding, active, temp stable' },
          { key: 'hydration', label: 'Hydration / Perfusion', value: d.hydration ?? '', hint: 'fontanelle, turgor, mucous membranes, cap refill — plus glucose: the hypoglycaemic neonate looks exactly like the septic one. Check glucose in every unwell neonate regardless of feeding history — treatment threshold is <2.6 mmol/L in an at-risk/symptomatic infant, and any level with neurological symptoms (jitteriness, lethargy, apnoea, seizures) is an emergency at any reading. Ladder: early feed → recheck 30-60min → IV 10% dextrose bolus (~2 mL/kg) + maintenance infusion → escalate the glucose infusion rate if refractory, with a "critical sample" (glucose, insulin, cortisol, GH, lactate, ammonia) sent AT a persistently low reading', placeholder: 'Hydration + perfusion findings, glucose if checked' },
        ];
      }
      if (subDept === 'malnutrition') {
        return [
          { key: 'anthropometry', label: 'Anthropometry', value: d.anthropometry ?? '', hint: 'weight, length/height, weight-for-height Z-score PLOTTED, MUAC — WHZ <-3 or MUAC <11.5cm (6-59m) = SAM; admission and discharge criteria both live in these numbers', placeholder: 'e.g. 6.1kg, 71cm, WHZ -3.4, MUAC 10.8cm' },
          { key: 'oedemaGrade', label: 'Nutritional Oedema', value: d.oedemaGrade ?? '', kind: 'select', options: ['None', '+ (both feet)', '++ (feet + lower legs/hands)', '+++ (generalised incl. face)'], hint: 'bilateral pitting oedema = SAM regardless of the weight (kwashiorkor) — and oedematous SAM carries the higher mortality; grade it daily, weight falls as oedema clears' },
          { key: 'appetiteTest', label: 'Appetite Test (RUTF)', value: d.appetiteTest ?? '', kind: 'select', options: ['Passed — eats RUTF portion', 'Failed — refuses/unable', 'Not done yet'], hint: 'the appetite test IS the triage: failed appetite or any complication = complicated SAM = inpatient F-75; passed + well = outpatient RUTF is safer than a hospital bed' },
          { key: 'feedingPhase', label: 'Feeding Phase', value: d.feedingPhase ?? '', kind: 'select', options: ['Stabilisation — F-75', 'Transition', 'Rehabilitation — F-100 / RUTF'], hint: 'F-75 FIRST: pushing volume, protein or sodium in the first days kills (refeeding syndrome, heart failure) — transition only when oedema is settling and appetite returns' },
          { key: 'complicationsCheck', label: 'Complications Check', value: d.complicationsCheck ?? '', kind: 'textarea', hint: 'the WHO first steps: glucose (hypoglycaemia), temperature (hypothermia — both signs of sepsis in SAM), dehydration assessed CAUTIOUSLY (signs overlap SAM; rehydrate with ReSoMal orally — IV fluids only in shock), infection (often afebrile), eyes (vitamin A), skin/dermatosis', placeholder: 'Glucose, temp, hydration, infection screen, eyes, skin' },
        ];
      }
      return [
        { key: 'growth', label: 'Growth (plotted on RTHB)', value: d.growth ?? '', hint: 'weight PLOTTED on the RTHB curve with centile, plus height/HC — a written weight misses the fall across centiles; the trend across previous visits is the diagnosis', placeholder: 'e.g. 8.4kg — plotted, fallen from 25th to 3rd centile' },
        { key: 'muac', label: 'MUAC', value: d.muac ?? '', hint: '6-59 months: <11.5cm = SAM, 11.5-12.4 = MAM — MUAC catches the wasted child whose weight-for-age still looks acceptable, and it takes ten seconds', placeholder: 'e.g. 13.2 cm' },
        { key: 'imciDangerSigns', label: 'IMCI Danger Signs', value: d.imciDangerSigns ?? '', kind: 'select', options: ['None — all four screened negative', 'Unable to drink/breastfeed', 'Vomits everything', 'Convulsions (this illness)', 'Lethargic / unconscious', 'More than one sign'], hint: 'the four general danger signs are screened in EVERY sick child under 5, on arrival AND repeatedly through the encounter — not a one-off box ticked at triage. Any one reclassifies as severe: admit, treat pre-referral, do not send home, and it OVERRIDES whatever syndrome-specific algorithm you were about to apply. Document "screened negative" explicitly', placeholder: '' },
        { key: 'hydration', label: 'Hydration Status', value: d.hydration ?? '', hint: 'IMCI classification: sunken eyes, skin pinch (≥2s), drinking eagerly vs unable, lethargy — these signs pick Plan A/B/C: oral vs supervised ORS vs IV', placeholder: 'e.g. no sunken eyes, pinch immediate — no dehydration (Plan A)' },
      ];
    },
  },
};
